main: org.bruno.elytraEssentials.ElytraEssentials
author: CodingMaestro
name: ElytraEssentials
version: 2.2.0
api-version: '1.21'
load: STARTUP
folia-supported: true
description: A powerful plugin to manage Elytra flight and equipment features.
website: https://www.spigotmc.org/resources/elytraessentials.126002/
softdepend: [Vault, PlaceholderAPI, PacketEvents]
commands:
  elytraessentials:
    description: Main command for ElytraEssentials.
    usage: /ee <subcommand>
    aliases: [ ee ]

permissions:
  elytraessentials.*:
    description: "Grants access to all ElytraEssentials plugin features and commands."
    default: op
    children:
      elytraessentials.command.*:
        description: "Allows the use of all ElytraEssentials commands."
        default: op
        children:
          # Command Permissions
          elytraessentials.command.help:
            default: true
            description: "Allows the use of the /ee help command."
          elytraessentials.command.reload:
            default: op
            description: "Allows reloading the plugin configuration."
          elytraessentials.command.flighttime:
            default: op
            description: "Allows managing player flight time."
          elytraessentials.command.shop:
            default: true
            description: "Allows opening the effects shop GUI."
          elytraessentials.command.effects:
            default: true
            description: "Allows opening the owned effects GUI."
          elytraessentials.command.effects.clear:
            default: true
            description: "Allows clearing an active elytra effect."
          elytraessentials.command.effects.give:
            description: "Allows giving an effect to a player."
            default: op
          elytraessentials.command.effects.remove:
            description: "Allows removing an effect from a player."
            default: op
          elytraessentials.command.effects.list:
            description: "Allows listing a player's owned effects."
            default: op
          elytraessentials.command.stats:
            default: true
            description: "Allows viewing personal flight statistics."
          elytraessentials.command.stats.others:
            default: op
            description: "Allows viewing another player's statistics."
          elytraessentials.command.stats.reset:
            default: op
            description: "Allows resetting another player's statistics."
          elytraessentials.command.top:
            default: true
            description: "Allows viewing leaderboards."
          elytraessentials.command.forge:
            default: op
            description: "Allows using the Armored Elytra forge."
          elytraessentials.command.armor:
            default: true
            description: "Allows viewing Armored Elytra stats."
          elytraessentials.command.armor.repair:
            default: true
            description: "Allows repairing a worn Armored Elytra."
          elytraessentials.command.importdb:
            default: op
            description: "Allows restoring a database backup."
          elytraessentials.command.achievements:
            default: true
            description: "Allows opening the achievements GUI."
          elytraessentials.command.tandem.invite:
            default: true
            description: "Allows inviting a player to fly with you."
          elytraessentials.command.tandem.accept:
            default: true
            description: "Allows accepting a pending tandem flight invitation."
          elytraessentials.command.tandem.leave:
            default: true
            description: "Allows dismounting from a tandem flight."
          elytraessentials.command.upgrade:
            default: op
            description: "Allows open the GUI to upgrade armored elytra."

      elytraessentials.bypass.*:
        description: "Allows bypassing all plugin restrictions and limits."
        default: op
        children:
          # Bypass Permissions
          elytraessentials.bypass.speedlimit:
            default: op
            description: "Bypasses flight speed limits."
          elytraessentials.bypass.timelimit:
            default: op
            description: "Bypasses flight time limits."
          elytraessentials.bypass.equipment:
            default: op
            description: "Bypasses restrictions on equipping elytras."
          elytraessentials.bypass.boostcooldown:
            default: op
            description: "Bypasses the cooldown for elytra boosts."
          elytraessentials.bypass.combattag:
            default: op
            description: "Prevents the combat tag from disabling flight."

      elytraessentials.effect.*:
        default: op
        description: "Gives you access to all elytra effects"
        children:
          # Individual Effect Permissions
          elytraessentials.effect.fire:
            description: "Grants access to the Fire Trail effect."
            default: false
          elytraessentials.effect.water:
            description: "Grants access to the Water Trail effect."
            default: false
          elytraessentials.effect.ice:
            description: "Grants access to the Ice Shards effect."
            default: false
          elytraessentials.effect.void:
            description: "Grants access to the Inky Void effect."
            default: false
          elytraessentials.effect.heart:
            description: "Grants access to the Heart Trail effect."
            default: false
          elytraessentials.effect.arcane:
            description: "Grants access to the Arcane Trail effect."
            default: false
          elytraessentials.effect.emerald:
            description: "Grants access to the Emerald Spark effect."
            default: false
          elytraessentials.effect.witch:
            description: "Grants access to the Witch's Brew effect."
            default: false
          elytraessentials.effect.soulfire:
            description: "Grants access to the Soul Fire effect."
            default: false
          elytraessentials.effect.note:
            description: "Grants access to the Musical Flight effect."
            default: false
          elytraessentials.effect.cloud:
            description: "Grants access to the Cloud Surfer effect."
            default: false
          elytraessentials.effect.slime:
            description: "Grants access to the Slime Trail effect."
            default: false
          elytraessentials.effect.crit:
            description: "Grants access to the Critical Aura effect."
            default: false
          elytraessentials.effect.portal:
            description: "Grants access to the Ender's Wake effect."
            default: false
          elytraessentials.effect.spore:
            description: "Grants access to the Spore Bloom effect."
            default: false
          elytraessentials.effect.bubble:
            description: "Grants access to the Bubble Stream effect."
            default: false
          elytraessentials.effect.dragon:
            description: "Grants access to the Dragon Breath effect."
            default: false
          elytraessentials.effect.wax:
            description: "Grants access to the Waxed Wings effect."
            default: false
          elytraessentials.effect.explosion:
            description: "Grants access to the Explosive Trail effect."
            default: false
          elytraessentials.effect.smoke:
            description: "Grants access to the Smoke Screen effect."
            default: false
          elytraessentials.effect.totem:
            description: "Grants access to the Totem's Blessing effect."
            default: false
          elytraessentials.effect.lavadrip:
            description: "Grants access to the Lava Drip effect."
            default: false
          elytraessentials.effect.cherry:
            description: "Grants access to the Cherry Blossom effect (available for version >= 1.20)."
            default: false
          elytraessentials.effect.dolphin:
            description: "Grants access to the Dolphin's Grace effect."
            default: false
          elytraessentials.effect.damage:
            description: "Grants access to the Damage Flash effect."
            default: false

      # Feature Permissions
      elytraessentials.update.notify:
        default: op
        description: "Receives update notifications on join."
      elytraessentials.elytra.boost:
        default: op
        description: "Allows using the basic elytra boost."
      elytraessentials.elytra.superboost:
        default: op
        description: "Allows using the elytra super boost."
      elytraessentials.elytra.chargedjump:
        default: op
        description: "Allows using the charged jump takeoff."
      elytraessentials.elytra.autodeploy:
        default: op
        description: "Enables the emergency elytra auto-deploy feature."
      elytraessentials.elytra.tandemflight:
        default: op
        description: "Allows flying with a passenger using the Tandem Flight feature."